alert("Hello Babe!")
alert("I want to take this opportunity to tell you how grateful I am to have you.")
alert("I promise to keep cherishing you, loving you, and making you happy.")
alert("May the universe grant you all the miracles and wishes you deserve. ")
alert("Happy Birthday to you, wifey ko! \nI love you so much! 🤍")
